spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: test
#      username: admin
#      password:
#      database: test
      uri: ${DB_URI}
  jwt:
    secret: ${SECRET_KEY}
    expiration: 36000000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: ${NAVER_USER} #네이버 아이디
    password: ${NAVER_PASSWORD} #네이버 비밀번호
    properties:
      debug: true
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
  logging:
    level:
      com.nimatnemat: DEBUG
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
