spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: test
#      username: admin
#      password:
#      database: test
      uri: mongodb+srv://dongun3m:13792346asd@seondongun.cvaxniv.mongodb.net/restaurant_db
  jwt:
    secret: bmltYXRuZW1hdC1iYWNrZW5kcHJvamVjdC1qd3Qtc2VjcmV0a2V5LWp3dC1iYWNrZW5kcHJvamVjdC1tYWRlYnktc3ByaW5nYm9vdAo=
    expiration: 36000000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: zxvs112@naver.com #네이버 아이디
    password: zxvs1218 #네이버 비밀번호
    properties:
      debug: true
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
  logging:
    level:
      com.nimatnemat: DEBUG
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
